{% set version = "1.2.0" %}

package:
  name: mercantile
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/m/mercantile/mercantile-{{ version }}.tar.gz
  sha256: 5bc60d351f6bcae9a466552358af7fe5191dc48c4025a8e8aa7fdd71d81669ef

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mercantile=mercantile.scripts:cli

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - click >=3.0

test:
  imports:
    - mercantile
    - mercantile.scripts
  commands:
    - mercantile --help
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sgillies/mercantile
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Spherical mercator and XYZ tile utilities
  license_family: BSD

extra:
  recipe-maintainers:
    - ocefpaf
